apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-riker
  namespace: {{ .Values.argoNamespace | default "argocd" }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.argoProject | default "default" }}
  destination:
    namespace: default
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/rkhandelwal17/aussie-holiday-api.git
    targetRevision: main
    path: k8s
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
